/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        current: "currentColor",
        transparent: "transparent",
        "sky-1": "#0c1820",
        "sky-2": "#071d2a",
        "sky-3": "#082636",
        "sky-4": "#082d41",
        "sky-5": "#08354c",
        "sky-6": "#083e59",
        "sky-7": "#064b6b",
        "sky-8": "#005d85",
        "sky-9": "#68ddfd",
        "sky-10": "#8ae8ff",
        "sky-11": "#2ec8ee",
        "sky-12": "#eaf8ff",
        "slate-1": "#fbfcfd",
        "slate-2": "#f8f9fa",
        "slate-3": "#f1f3f5",
        "slate-4": "#eceef0",
        "slate-5": "#e6e8eb",
        "slate-6": "#dfe3e6",
        "slate-7": "#d7dbdf",
        "slate-8": "#c1c8cd",
        "slate-9": "#889096",
        "slate-10": "#7e868c",
        "slate-11": "#687076",
        "slate-12": "#11181c",
        "slate-1-dark": "#151718",
        "slate-2-dark": "#1a1d1e",
        "slate-3-dark": "#202425",
        "slate-4-dark": "#26292b",
        "slate-5-dark": "#2b2f31",
        "slate-6-dark": "#313538",
        "slate-7-dark": "#3a3f42",
        "slate-8-dark": "#4c5155",
        "slate-9-dark": "#697177",
        "slate-10-dark": "#787f85",
        "slate-11-dark": "#9ba1a6",
        "slate-12-dark": "#ecedee",
        "blue-items-default": "#16B1FF",
        "blue-items-hover": "#47C2FF",
        "blue-items-click": "#56BDF0",
        "blue-items-press": "#23ADF2",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
